(function(k){function N(a,b){var c=new XMLHttpRequest;c.onreadystatechange=function(){if(4===c.readyState){c.onreadystatechange=null;var a;200===c.status&&(a=c.responseText,0!==a.length&&"<"!==a.charAt(0))?b(a):b(!1)}};c.open("GET",a,!0);c.send(null)}function m(a,b){var c;if(a&&"object"===typeof a){var d=a.length;if("number"===typeof d){if(0===d)return;if(0 in a&&[d-1]in a){for(c=0;c<d&&!1!==b(a[c],c);++c);return}}for(c in a)if(a.hasOwnProperty(c)&&!1===b(a[c],c))break}}function C(){}function r(a,
b,c,d){a.addEventListener(b,c,Boolean(d))}function Y(a,b){m(b,function(b,d){a[d]=b});return a}function u(){return Date.now?Date.now():(new Date).getTime()}function D(a){var b=!1,c,d=!1,e=[];return function(f){b?f(c):(e.push(f),d||(d=!0,a(function(a){b=!0;d=!1;c=a;m(e,function(a){a(c)});e.length=0;e=null})))}}function O(a){a=parseInt(a,10);return isNaN(a)?!1:a}function Z(){h(function(a){function b(){var b=WeixinJSBridge;b.call("showOptionMenu");var d=a.toString();b.on("menu:share:appmessage",function(a){b.invoke("sendAppMessage",
{img_url:g.getImgUrl(),link:g.getUrl(d),desc:g.wxFriendDesc||g.desc,title:g.title},function(a){v(["_trackEvent","WXShareButton","gameShareWXFriend"]);E()})});b.on("menu:share:timeline",function(a){b.invoke("shareTimeline",{img_url:g.getImgUrl(),img_width:"300",img_height:"300",link:g.getUrl(d),desc:g.wxTimelineDesc||g.desc,title:g.wxTimelineDesc||g.desc||g.title},function(a){v(["_trackEvent","WXShareButton","gameShareWX"]);E()})});b.on("menu:share:weibo",function(a){b.invoke("shareWeibo",{content:g.getImgUrl(),
url:g.getUrl(d)},function(a){v(["_trackEvent","WXShareButton","gameShareWXweibo"]);E()})})}"undefined"!==typeof WeixinJSBridge?b():r(n,"WeixinJSBridgeReady",function d(){n.removeEventListener("WeixinJSBridgeReady",d,Boolean(void 0));"undefined"!==typeof WeixinJSBridge&&b()})})}function v(a){"undefined"!==typeof _hmt&&_hmt.push(a)}function x(a){var b=a[2];a=["http://liebao.tjweb.ijinshan.com/click/__infoc.gif?actionname=liebao_",a[0],"&type=",a[1]].join("");var c="";b&&m(b,function(a,b){c+="&"+encodeURIComponent(b)+
"="+encodeURIComponent(a)});(new Image).src=a+c+"&random="+u()}function E(){t.hide();if(!1!==g.doneJump)location.href=F;else{var a=g.afterShare;a&&a()}}function $(a){P.lastIndex=0;return a.replace(P,function(a,c){m(aa,function(d){if(d===c)return a="",!1});return a})}function G(a){var b=n.body;b&&a(b)}function Q(a,b){function c(){f.removeEventListener("load",d,Boolean(void 0));f.removeEventListener("error",e,Boolean(void 0))}function d(){c();R[a]=!0;b(!0)}function e(){c();b(!1)}if(R[a])return b(!0);
var f=new Image;r(f,"load",d);r(f,"error",e);f.src=a}function S(a,b){var c=this;Q(b,function(d){d&&c.shown&&G(function(d){h(function(f){var w=c.conf;c.href=a;c.style.backgroundImage="url("+b+")";d.appendChild(c);y(["_trackEvent","ad_show",p+"_"+f.os+"_"+f.browser+"_"+w.p+"_"+w.n+"_show"]);x([203,80,{stype:2,name:p,id:w.n,ua:f.browser,dev:f.os,op:0}])})})})}function ba(a,b){var c=this;Q(b,function(d){d&&c.shown&&G(function(d){function f(){var a=k.innerWidth,b=k.innerHeight,d=0.8*Math.min(a,b)|0;Y(c.style,
{width:d+"px",height:d+"px",top:((b-d)/2|0)+"px",left:((a-d)/2|0)+"px"})}function w(){d.removeEventListener("click",l,Boolean(void 0));k.removeEventListener("resize",s,Boolean(void 0));k.removeEventListener("orientationchange",s,Boolean(void 0));c._oc=null}function l(a){a.target!==c&&(c.shown&&1E3<u()-c.shown)&&(a.stopPropagation(),w(),H.hide("banner"))}function s(){g||(g=!0,f(),setTimeout(f,500),setTimeout(function(){g=!1;f()},1E3))}var g=!1;c.href=a;c.style.backgroundImage="url("+b+")";var I=c.conf;
h(function(a){y(["_trackEvent","ad_show",p+"_"+a.os+"_"+a.browser+"_"+I.p+"_"+I.n+"_show"]);f();d.appendChild(c);r(k,"resize",s);r(k,"orientationchange",s);r(d,"click",l);c._oc=w;x([203,80,{stype:3,name:p,id:I.n,ua:a.browser,dev:a.os,op:0}])})})})}function J(a){z(function(b){if(b=b[a]){var c=K[a]=Math.random()*b.length|0;b=b[c];(new Image).src=b.img_url}})}function ca(a,b){z(function(c){if(c=c[a])K.hasOwnProperty(a)||J(a),c=c[K[a]],J(a),b(c)})}var q=k.LBShare;q||(q=k.LBShare={});Object.create||(Object.create=
function(a){C.prototype=a;a=new C;C.prototype=null;return a});Date.now||(Date.now=function(){return(new Date).getTime()});var A=function(){function a(a,c){if(c){var f=Date.now()+String(Math.random());a.token=f;b[f]=c}prompt(JSON.stringify({class_name:"com.ijinshan.browser.KInjectionJavaScriptObject",params:a,sync:!1}),"3.1415926535")}var b=Object.create(null);__callback=function(a){if(a in b){var c=b[a];delete b[a];var f=[];m(arguments,function(a,b){0!==b&&f.push(a)});c.apply(null,f)}};var c={upgradeApk:function(b,
c,f){a({function_name:"upgradeApk",versioncode:b,description:c,apkurl:f})},send:a};m(["getUid","getAid"],function(b){c[b]=function(c){h(function(f){"kuwan"===f.browser?301012<=f.kuwanVersion?a({function_name:b},function(a){c(!0,a)}):c(!1,"Kuwan version less than 301012"):c(!1,"Not kuwan")})}});return c}(),n=document,T={weixin:{check:function(a){if(/MicroMessenger/.test(a))return setTimeout(Z,0),!0}},cm:{check:function(a){return k.android&&/CM/.test(a)},updateData:function(a){try{k.android.updatesharedata(a.title,
a.imgUrl,a.desc,a.url)}catch(b){}},callShare:function(){try{k.android.sharescore()}catch(a){}},adOnClick:function(a){if(/\.apk$/.test(a)&&k.android&&"undefined"!==typeof k.android.downloadapp)return setTimeout(function(){try{k.android.downloadapp("com.gkuwan.cm",a,"\u514d\u8d39\u5c0f\u6e38\u620f","")}catch(b){}},0),!1}},kuwan:{check:function(a,b){var c=a.match(/Gkuwan\/(\d+)/i);if(c)return c=b.kuwanVersion=O(c[1]),b.kuwanNew=c?301011<=c:!1,!0},checkAsync:function(a){var b=k.gkuwan;if(b)return b=a.kuwanVersion=
O(b),a.kuwanNew=b?301011<=b:!1,!0},updateData:function(a,b){if(b.kuwanNew)A.send({function_name:"updateShareData",title:a.title,cont:a.desc,imgurl:a.imgUrl,url:a.url});else try{k.updateclient.updatesharedata(a.title,a.imgUrl,a.desc,a.url)}catch(c){}},callShare:function(a){if(a.kuwanNew)A.send({function_name:"shareScore"});else try{k.updateclient.sharescore()}catch(b){}}},liebao:{check:function(a){return/LieBaoFast/.test(a)},updateData:function(a){var b=a.desc+" "+a.url+" @\u730e\u8c79\u6d4f\u89c8\u5668 http://m.liebao.cn/";
if("undefined"!==typeof __injectionJavaScriptObject___&&__injectionJavaScriptObject___.updateShareData)try{__injectionJavaScriptObject___.updateShareData(a.title,a.imgUrl,b,a.url)}catch(c){}else prompt(JSON.stringify({class_name:"com.ijinshan.browser.KInjectionJavaScriptObject",params:{function_name:"updateShareData",title:a.title,cont:b,imgurl:a.imgUrl,url:a.url},sync:!1}),"3.1415926535")},callShare:function(){if("undefined"!==typeof __injectionJavaScriptObject___&&__injectionJavaScriptObject___.shareScore)try{__injectionJavaScriptObject___.shareScore()}catch(a){}else prompt(JSON.stringify({class_name:"com.ijinshan.browser.KInjectionJavaScriptObject",
params:{function_name:"shareScore"},sync:!1}),"3.1415926535")}}},h=D(function(a){var b={toString:function(){return b.os+"_"+b.browser}},c=k.navigator.userAgent,d,e="pc",f=["adOnClick","updateData","callShare"];m(T,function(a,e){if(a.check(c,b))return d=e,m(f,function(c){b[c]=a[c]}),!1});var g=n.referrer;g&&-1!==g.indexOf("LBGameCenter")&&(b.LBGameCenter=!0);switch(!0){case /iPad|iPhone/.test(c):e="ios";break;case /Android/.test(c):e="android";break;case /Mobile/.test(c):e="mobile"}b.os=e;if(d)b.browser=
d,a(b);else{var l=n.createElement("script");l.src="http://www.liebao.cn/game/js/client.js";var s=!1;l.onload=function(){clearTimeout(h);l.onload=null;l.onerror=null;if(!s){s=!0;var c;m(T,function(a,d){var e=a.checkAsync;if(e&&e(b))return c=b.browser=d,m(f,function(c){b[c]=a[c]}),!1});c||(b.browser="browser");a(b)}};l.onerror=function(){clearTimeout(h);l.onload=null;l.onerror=null;s||(s=!0,b.browser="browser",a(b))};var h=setTimeout(function(){l.onload=null;l.onerror=null;s||(s=!0,b.browser="browser",
a(b))},3E3);n.documentElement.appendChild(l)}}),U=u(),g={},F="http://dl.game.35go.net/weixin/game/kw.html",B=location.protocol+"//"+location.host,V=location.pathname,p="unknownGame";(function(){var a=V.match(/^\/game\/([^\/]+)/);a?p=a[1]:(a=n.getElementsByTagName("meta"),m(a,function(a){if("game-id"===a.getAttribute("name")&&(a=a.getAttribute("content")))return p=a,!1}));F+="?f="+p})();var L=D(function(a){N("/game/conf/jumpCloud.json?t="+U,function(b){if(b){var c;try{c=JSON.parse(b)}catch(d){}B="http://q"+
Math.floor(5E3*Math.random())+"."+c.jumphost}a(B)})});L(function(){h(function(a){"www.liebao.cn"===location.host&&"weixin"===a.browser})});var y=function(){function a(){return c}var b=k.Image,c={};return function(d){"undefined"!==typeof _hmt&&(Image=a,v(d),Image=b,d=c.src,(new b).src=d.replace(/si=[^&]+/,"si=b3fedc43bfd632b7ef6525e4b6930685"),(new b).src=d)}}(),P=/&?([^&\?=]+)(?:=[^&\?=]+)?/g,aa="t f from code state _lw isappinstalled".split(" ");g.getUrl=function(a){var b=
n.createElement("a"),c=location.search;b.href=g.url||B+V+(c&&-1!==c.indexOf("?")?c:"");var c=$(b.search),d=g.wxOpenId;d||"undefined"===typeof LBWx||(d=LBWx.getUserInfoLocal().openid);"?"===c&&(c="");b.search=c+(c?"&":"?")+("f="+(a?a:"unknownShare"))+(d?"&_lw="+encodeURIComponent(d):"")+"&t="+U;return b.href};g.getImgUrl=function(){var a=g.imgUrl;if(a){var b=n.createElement("a");b.href=a;return b.href}return"http://www.liebao.cn/game/img/icon.png"};var t={t:0,_div:void 0,show:function(){var a=t._div;
if(!a){var a=t._div=n.createElement("div"),b="position:fixed;top:0;left:0;width:100%;height:100%;z-index:100;background:";h(function(c){b+="browser"===c.browser?"url(http://www.liebao.cn/game/iq_test/images/share_tip_2.png?v=1) center bottom rgba(0,0,0,.6) no-repeat;":"url(http://www.liebao.cn/game/iq_test/images/share_tip.png?v=1) 50% 0 rgba(0,0,0,.6) no-repeat;";b+="background-size:contain";a.style.cssText=b});r(a,"touchstart",t.hide);r(a,"mousedown",t.hide)}G(function(b){t.t=u();b.appendChild(a)})},
hide:function(){if(!(1E3>u()-t.t)){var a=t._div;if(a){var b=a.parentNode;b&&b.removeChild(a)}}}};q.updateData=function(a){m(a,function(a,c){g[c]=a});h(function(a){var c=a.toString(),d=a.updateData;d&&L(function(){d({title:g.title,imgUrl:g.getImgUrl(),desc:g.desc,url:g.getUrl(c)},a)})})};q.callShare=function(){h(function(a){v(["_trackEvent","shareBtn",a.toString()]);var b=a.callShare;b?L(function(){b(a)}):t.show()})};q.more=function(){v(["_trackEvent","button","more"]);location.href="/game/?f="+p};
q.statScore=function(a){v(["_trackEvent","button","end",a])};q.getRank=function(a,b){var c;if("number"===typeof b)c=100*a/b;else{var d=Infinity,e=-d,f,g,l=e;m(b,function(b,k){var h=parseInt(k,10);if(!isNaN(h)&&0<=h&&100>=h){l=Math.max(l,b);if(b===a)return c=h,!1;b<a?e<b&&(f=h,e=b):d>b&&(g=h,d=b)}});void 0===c&&(void 0===f&&(e=f=0),void 0===g&&(g=100,d=2*l),c=f+(a-e)*(g-f)/(d-e))}return Math.max(0.1,Math.min(99.9,isNaN(c)?0:c)).toFixed(1)+"%"};var z=D(function(a){N("/game/conf/"+p+".json?"+(u()/5/
60/1E3|0),function(b){var c,d=!1;if(b){var e;try{e=JSON.parse(b)}catch(f){}e?h(function(b){if(c="ios"===b.os?e.ios:e.android)b=b.browser,(c="weixin"===b||"kuwan"===b?c[b]:c.other)&&(d=c);a(d)}):a(!1)}else a(!1)})}),R={},K={},da=99,M={},H={show:function(a){ca(a,function(b){var c,d;if(b&&(c=b.img_url)&&(d=b.link_url)){var e=M[a];if(!e){e=M[a]=n.createElement("a");e.target="_blank";var f;h(function(a){f=a});r(e,"click",function(a){if(e===a.target&&f){var b=f.adOnClick;b&&!1===b(e.href)&&(a.preventDefault?
a.preventDefault():a.returnValue=!1)}});r(n,"touchend",function(b){b.target===e&&h(function(b){var c=e.conf;y(["_trackEvent","ad_click",p+"_"+b.os+"_"+b.browser+"_"+c.p+"_"+c.n+"_click"]);x([203,80,{stype:"banner"===a?3:2,name:p,id:c.n,ua:b.browser,dev:b.os,op:1}])})});switch(a){case "top":e.style.cssText="-webkit-tap-highlight-color:rgba(0,0,0,0);position:fixed;height:0;background:#fff 50% 50% no-repeat;background-size:100% 100%;width:100%;padding-bottom:16.67%;left:0;top:0";e.setImg=S;break;case "footer":e.style.cssText=
"-webkit-tap-highlight-color:rgba(0,0,0,0);position:fixed;height:0;background:#fff 50% 50% no-repeat;background-size:100% 100%;width:100%;padding-bottom:16.67%;left:0;bottom:0";e.setImg=S;break;case "banner":e.style.cssText="-webkit-tap-highlight-color:rgba(0,0,0,0);position:fixed;height:0;background:#fff 50% 50% no-repeat;background-size:100% 100%;";e.setImg=ba;var g=n.createElement("div");g.style.cssText="position:absolute;top:2.5%;right:2.5%;width:12%;height:12%;cursor:pointer;-webkit-tap-highlight-color:rgba(0,0,0,0)";
e.appendChild(g);r(n,"touchend",function(a){a.target===g&&(a.preventDefault?a.preventDefault():a.returnValue=!1,a.stopPropagation(),e.shown&&1E3<u()-e.shown&&((a=e._oc)&&a(),H.hide("banner")))},!0)}}e.shown||(e.shown=u(),e.style.zIndex=++da,e.setImg(d,c),b=b.hasOwnProperty("adid")?b.adid:void 0,e.conf={n:b,p:a})}})},hide:function(a){var b=M[a];if(b&&b.shown){var c=b._oc;c&&c();b.shown=!1;(c=b.parentNode)&&c.removeChild(b);h(function(c){var e=b.conf||{p:-1,n:-1};y(["_trackEvent","ad_close",p+"_"+c.os+
"_"+c.browser+"_"+e.p+"_"+e.n+"_close"]);x([203,80,{stype:"banner"===a?3:2,name:p,id:b.conf.n,ua:c.browser,dev:c.os,op:2}])})}}},ea={top:0,footer:0,banner:0},W=0;q.showAd=function(a){var b=a.pos,c=a.hide;h(function(d){if(!d.LBGameCenter&&ea.hasOwnProperty(b)){if("banner"===b&&(d=a.bannerShowOps)){++W;var e=!1;m(d,function(a){if(W===a)return e=!0,!1});if(!e)return}z(function(a){if(a)H[c?"hide":"show"](b)})}})};var X=q._sd;X&&(q.updateData(X),q._sd=null);z(function(a){a&&m(a,function(a,c){J(c)})});
h(function(a){x([203,80,{stype:1,name:p,ua:a.browser,dev:a.os}]);"cm"===a.browser&&x([203,80,{stype:4,url:location.href.replace(/^http:\/\/|\?.*$/g,"")}])});q.kuwanInvoke=function(a,b){if(A.hasOwnProperty(a))A[a](b);else b(!1,"Method "+a+" not exists")}})(window);
